# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
workspace "../CFNetworkKit.xcworkspace"

target 'CFNetworkKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CFNetworkKit
  pod 'AFNetworking', '~> 3.0'
  pod 'CFFoundation', :git => 'git@github.com:rongfei3380/CFFoundation.git', :branch => 'master'
  target 'CFNetworkKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
